//
//  RecipeDefines.h
//  iHungryMac
//
//  Created by Mark on 11/18/09.
//  Copyright 2009 __MyCompanyName__. All rights reserved.
//
//// MUST BE SET AT VERSION RELEASE -NOT USED FOR VIRGIN

//#define RES_DATA_VERSION_NUMBER @"0"
//#define RES_DATA_VERSION_NUMBER @"1.46"

#define RES_DATA_VERSION_NUMBER @"1.50"
#define NEW_APP_VERSION_NUMBER @"1.1"
//#define RES_MAX_RECIPE_ID 89
////

#define DEFAULTS_APP_VERSION_NUMBER_KEY @"DG_DefaultsAppVersionNumber"
#define DEFAULTS_DATA_VERSION_NUMBER_KEY @"DG_DefaultsDataVersionNumber"



//#define CURRENT_DATA_VERSION_NUMBER @"1.50" fetchFrom VersionXml

#define CATEGORY_NAME_LENGTH_WARNING @"Category Name Length Out Of Range"
#define RECIPE_NAME_LENGTH_WARNING @"Recipe Name Length Out Of Range"
#define MAX_CATEGORY_NAMESHORT_LENGTH 23
#define MAX_CATEGORY_NAME_LENGTH 70
#define MIN_CATEGORY_NAME_LENGTH 2
#define MAX_RECIPE_NAME_LENGTH 70
#define MAX_PHOTO_NAME_LENGTH 50
#define MIN_PHOTO_NAME_LENGTH 1
#define MIN_RECIPE_NAME_LENGTH 2
#define CATEGORY1_DX 1
#define CATEGORY2_DX 2

#define RECIPE_NAME_TAG 0
#define RECIPE_NAME_SHORT_TAG 1
#define CATEGORY1_TAG 2
#define CATEGORY2_TAG 3
#define PHOTO_TAG 4
#define INGREDIENTS_TAG 5
#define DIRECTIONS_TAG 6
#define COMMENTS_TAG 7
#define PHOTO_NAME_TAG 8


#define 	RECIPE_NAME_SECTION_DX 0	
#define 	RECIPE_NAME_OFFSET 8
#define  RECIPE_NAME_TEXTFIELD_WIDTH 300
#define  RECIPE_NAME_TEXTFIELD_HEIGHT 40
//#define  RECIPE_NAME_TEXTFIELD_ROW_HEIGHT 50
#define  RECIPE_NAME_TEXTFIELD_ROW_HEIGHT 44

#define 	CATEGORIES_SECTION_DX 1	
#define 	CATEGORIES_OFFSET 8
#define  CATEGORIES_TEXTVIEW_WIDTH 300
#define  CATEGORIES_TEXTVIEW_HEIGHT 40

#define  CATEGORIES_ROW_HEIGHT 44

#define EMAIL_PHOTO_SECTION_DX 0

/*
#define 	CATEGORY2_SECTION_DX 2	
#define 	CATEGORY2_OFFSET 8
#define  CATEGORY2_TEXTVIEW_WIDTH 300
#define  CATEGORY2_TEXTVIEW_HEIGHT 40
#define  CATEGORY2_TEXTVIEW_ROW_HEIGHT 50	
*/
#define 	INGREDIENTS_SECTION_DX 2	
#define 	INGREDIENTS_OFFSET 0
#define  INGREDIENTS_TEXTVIEW_WIDTH 300
//#define  INGREDIENTS_TEXTVIEW_HEIGHT 50
//#define  INGREDIENTS_TEXTVIEW_ROW_HEIGHT 60	
#define  INGREDIENTS_TEXTVIEW_HEIGHT 44
#define  INGREDIENTS_TEXTVIEW_ROW_HEIGHT 44	

#define 	DIRECTIONS_SECTION_DX 3	
#define 	DIRECTIONS_OFFSET 8
#define  DIRECTIONS_TEXTVIEW_WIDTH 300
#define  DIRECTIONS_TEXTVIEW_HEIGHT 100
#define  DIRECTIONS_TEXTVIEW_ROW_HEIGHT 110	

#define 	COMMENTS_SECTION_DX 4	
#define 	COMMENTS_OFFSET 8
#define  COMMENTS_TEXTVIEW_WIDTH 300
#define  COMMENTS_TEXTVIEW_HEIGHT 100
#define  COMMENTS_TEXTVIEW_ROW_HEIGHT 110

#define 	PHOTO_SECTION_DX 5	
#define 	PHOTO_OFFSET 12
/*
#define  PHOTO_IMAGEVIEW_WIDTH 40
#define  PHOTO_IMAGEVIEW_HEIGHT 40
#define  PHOTO_IMAGEVIEW_ROW_HEIGHT 50
*/
#define  PHOTO_IMAGEVIEW_WIDTH 50
#define  PHOTO_IMAGEVIEW_HEIGHT 50
#define  PHOTO_IMAGEVIEW_ROW_HEIGHT 60

#define kTextViewLandscapeWidth 469
#define kTextViewLandscapeHeightEditing 94
#define kTextViewLandscapeHeight 277
#define kTextViewPortraitWidth 329
#define kTextViewPortraitHeight 416
#define kTextViewPortraitHeightEditing	 200

//#define CATEGORY_PICKER_WIDTH_PORT_IPAD 600
#define CATEGORY_PICKER_HEIGHT_PORT_IPAD 432.0
#define CATEGORY_PICKER_X_PORT_OFFSET 20.0
#define CATEGORY_PICKER_Y_PORT_OFFSET 334.0

#define CATEGORY_PICKER_HEIGHT_LAND_IPAD 360.0
#define CATEGORY_PICKER_X_LAND_OFFSET 20.0
#define CATEGORY_PICKER_Y_LAND_OFFSET 334.0

#define ADD_CAT_BUTTON_TAG 100
#define DEL_CAT_BUTTON_TAG 101
#define EDIT_CAT_BUTTON_TAG 102

#define SEARCHBAR_TAG 103

#define ADD_RX_BUTTON_TAG 104
#define DEL_RX_BUTTON_TAG 105
#define EDIT_RX_BUTTON_TAG 106